using Domain.Entities.Publications;

namespace Domain.Entities.RecomendationEntities;

public class PublicationTag
{
    public string PublicationId { get; set; } = string.Empty;
    public Publication Publication { get; set; } = null!;
    public int TagId { get; set; }
    public Tag Tag { get; set; } = null!;
    public bool IsAutoGenerated { get; set; }
}