using System.Reflection.Metadata;
using Application.DTOs.TagDTOs;
using Application.Features.Tags.Commands;
using Application.Features.Tags.Queries;
using Application.Helpers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace API.Controllers;

public class TagController : BaseApiController
{
    [Authorize]
    [HttpPost("add-tag")]
    public async Task<ActionResult> AddTag(string publicationId, CreateTagDto tagDto, CancellationToken ct)
    {
        var userId = User.GetUserId();
        return HandleResult(await Mediator.Send(new AddTag.Command
        {
            UserId = userId, PublicationId = publicationId,
            TagDto = tagDto
        }, ct));
    }

    [Authorize]
    [HttpPost("add-tags")]
    public async Task<ActionResult> AddTags(string publicationId, CreateTagsDto tagsDto, CancellationToken ct)
    {
        var userId = User.GetUserId();
        return HandleResult(await Mediator.Send(new AddTags.Command
        {
            UserId = userId,
            PublicationId = publicationId,
            TagsDto = tagsDto
        },ct));
    }

    [Authorize]
    [HttpPost("set-tag")]
    public async Task<ActionResult> SetTag(string publicationId, int tagId, CancellationToken ct)
    {
        var userId = User.GetUserId();
        return HandleResult(await Mediator.Send(new SetTag.Command
        {
            UserId = userId,
            PublicationId = publicationId,
            TagId = tagId
        }, ct));
    }

    [Authorize]
    [HttpPost("set-tags")]
    public async Task<ActionResult> SetTags(string publicationId, List<int> tagIds, CancellationToken ct)
    {
        var userId = User.GetUserId();
        return HandleResult(await Mediator.Send(new SetTags.Command
        {
            UserId = userId,
            PublicationId = publicationId,
            TagIds = tagIds
        }, ct));
    }

    [Authorize]
    [HttpDelete("tag-publication")]
    public async Task<ActionResult> RemoveTagPublication(string publicationId, int tagId, CancellationToken ct)
    {
        var userId = User.GetUserId();
        return HandleResult(await Mediator.Send(new DeleteTagPublication.Command
        {
            UserId = userId,
            PublicationId = publicationId,
            TagId = tagId
        }, ct));
    }

    [HttpGet("tag-search")]
    public async Task<ActionResult> SearchTags([FromQuery] string searchName, CancellationToken ct)
    {
        return HandleResult(await Mediator.Send(new SearchTags.Query
        {
            SearchName = searchName
        }, ct));
    }

    [HttpGet("tags-publication")]
    public async Task<ActionResult> GetTagsForPublication(string publicationId, CancellationToken ct)
    {
        return HandleResult(await Mediator.Send(new GetTagsForPublication.Query
        {
            PublicationId = publicationId
        }, ct));
    }

    [HttpGet("generate-tags")]
    public async Task<ActionResult> GenerateTagsForPublication(string publicationId, CancellationToken ct)
    {
        var userId = User.GetUserId();
        return HandleResult(await Mediator.Send(new GetAutoGeneratedTags.Query
        {
            PublicationId = publicationId,
            UserId = userId
        }, ct));
    }

    [HttpPost("save-generated-tags")]
    public async Task<ActionResult> SaveGeneratedTagsForPublication([FromQuery] string publicationId,
        [FromBody] List<GeneratedTagDto> generatedTags, CancellationToken ct)
    {
        var userId = User.GetUserId();

        return HandleResult(await Mediator.Send(new SaveAutoGeneratedTags.Command
        {
            UserId = userId,
            PublicationId = publicationId,
            GeneratedTags = generatedTags
        }, ct));
    }

}