using Application.Interfaces.Repositories;
using Domain.Entities.RecomendationEntities;
using Microsoft.EntityFrameworkCore;

namespace Infrastructure.Repositories;

public class TagRepository(ApplicationDbContext context) : ITagRepository
{
    public async Task<int> AddTagAsync(Tag tag, CancellationToken ct)
    {
        await context.Tags.AddAsync(tag, ct);
        return tag.Id;
    }

    public async Task<List<int>> AddTagsAsync(List<Tag> tags, CancellationToken ct)
    {
        await context.Tags.AddRangeAsync(tags, ct);
        var ids = tags.Select(x => x.Id).ToList();
        return ids;
    }

    public async Task AddTagsToPublicationAsync(string publicationId, List<Tag> tags, CancellationToken ct)
    {
        var publicationTags = tags.Select(tag => new PublicationTag
        {
            PublicationId = publicationId,
            TagId = tag.Id,
            IsAutoGenerated = false
        });

        await context.PublicationTags.AddRangeAsync(publicationTags, ct);
    }

    public async Task SetTagForPublicationAsync(string publicationId, int tagId, CancellationToken ct)
    {
        await context.PublicationTags.AddAsync(
            new PublicationTag
            {
                PublicationId = publicationId,
                TagId = tagId,
                IsAutoGenerated = false
            }, ct);
    }

    public async Task SetTagsForPublicationAsync(string publicationId, List<int> tagIds, CancellationToken ct)
    {
        var publicationTags = tagIds.Select(tagId => new PublicationTag
        {
            PublicationId = publicationId,
            TagId = tagId,
            IsAutoGenerated = false
        });

        await context.PublicationTags.AddRangeAsync(publicationTags, ct);
    }

    public async Task<Tag?> GetTagByIdAsync(int tagId, CancellationToken ct)
    {
        var tag = await context.Tags.Where(x => x.Id == tagId).FirstOrDefaultAsync(ct);
        return tag;
    }

    public async Task<List<Tag>> GetTagsForPublicationAsync(string publicationId, CancellationToken ct)
    {
        var tags = await context.PublicationTags.Where(x => x.PublicationId == publicationId).Select(x => x.Tag)
            .ToListAsync(ct);
        return tags;
    }

    public async Task<List<Tag>> SearchTagsByNameAsync(string name, CancellationToken ct)
    {
        return await context.Tags
            .Where(t => EF.Functions.ILike(t.Name, $"{name}%"))
            .OrderByDescending(t => t.Publications.Count).ThenByDescending(t => t.Name)
            .Take(20)
            .ToListAsync(ct);
    }

    public async Task DeleteTagAsync(int tagId, CancellationToken ct)
    {
        if (!await IsTagExists(tagId, ct))
            return;

        var tag = await context.Tags.FindAsync(tagId, ct);

        context.Tags.Remove(tag!);
    }

    public async Task DeleteTagConnectionAsync(int tagId, string publicationId, CancellationToken ct)
    {
        if (!await IsTagPublicationExists(tagId, publicationId, ct))
            return;
        
        var tag = await context.PublicationTags.Where(x => x.TagId == tagId && publicationId == x.PublicationId)
            .FirstOrDefaultAsync(ct);

        context.PublicationTags.Remove(tag!);
    }

    public async Task<bool> IsTagExists(int tagId, CancellationToken ct)
    {
        return await context.Tags.AnyAsync(x => x.Id == tagId, ct);
    }

    public async Task<bool> IsTagPublicationExists(int tagId, string publicationId, CancellationToken ct)
    {
        return await context.PublicationTags.AnyAsync(x => x.TagId == tagId && x.PublicationId == publicationId, ct);
    }

    public async Task<int> GetTagsAmountByPublicationIdAsync(string publicationId, CancellationToken ct)
    {
        if (!await context.Publications.AnyAsync(x => x.Id == publicationId, ct))
            return -1;

        var amount = await context.PublicationTags.Where(x => x.PublicationId == publicationId).CountAsync(ct);
        return amount;
    }

    public async Task<(List<Tag> existing, List<Tag> newTags)> SplitExistingAndNewTagsAsync(
        List<Tag> tags, CancellationToken ct)
    {
        var tagNames = tags.Select(t => t.Name).ToList();
    
        var existing = await context.Tags
            .Where(t => tagNames.Contains(t.Name))
            .ToListAsync(ct);

        var existingNames = existing.Select(t => t.Name).ToHashSet();
    
        var newTags = tags
            .Where(t => !existingNames.Contains(t.Name))
            .ToList();

        return (existing, newTags);
    }
}