using Application.Core;
using Application.DTOs.TagDTOs;
using Application.Interfaces.Services;

namespace Application.Features.Tags.Queries;

public class GetAutoGeneratedTags
{
    public class Query : IRequest<Result<List<GeneratedTagDto>>>
    {
        public required string UserId { get; set; }
        public required string PublicationId { get; set; }
    }
    
    public class Handler(IPublicationTagService publicationTagService) : IRequestHandler<Query, 
        Result<List<GeneratedTagDto>>>
    {
        public async Task<Result<List<GeneratedTagDto>>> Handle(Query request, CancellationToken cancellationToken)
        {
            return await publicationTagService.GenerateTags(request.PublicationId, request.UserId, cancellationToken);
        }
    }
}